### ISSUE TITLE
Footers: HTML

### ISSUE THREAD

**Issue by V-Valkiriya** [HYF-Class19/agile-development-loruki-group-1#13]
## The footers

- [ ] `HTML`
- [ ] `<div>` classes
-  [ ] `<h1>` for loruki title
- [ ] `<p>` paragraph for copyright license
- [ ] `<nav>` navigation bar for home, features & docs
- [ ]   `<a>` social media links

**Comment by galalkoro98** [comment]
perfiect @V-Valkiriya
